spring:
  jpa:
    generate-ddl: false

    show-sql: false

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/swagger
    username: postgres
    password: 123

server:
  port: 8010

application:
  swaggerHome: swagger-ui.html
  user:
    role: USER
  jwtSecret: secret
  jwtExpirationMs: 86400000